server:
  port: 8082
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${google.client_id}
            client-secret: ${google.client_secret}
            scope: openid,email
            client-name: Sign in with Google
        provider:
          google:
            user-name-attribute: email
  config:
    activate:
      on-profile: dev
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth2_server
    username: lobur
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  application:
    name: oauth2-server
logging:
  level:
    org:
      springframework:
        security: info
    root: info
