version: '3'

services:
  data-generator:
    build:
      context: .
      dockerfile: dockerfiles/data.dockerfile
    image: 'data-generator'
    container_name: data-generator
    depends_on:
      - postgres-resource
    ports:
      - "9095:9095"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_RESOURCE_URL=jdbc:postgresql://postgres-resource:${POSTGRES_PORT}/${RESOURCE_DB}