jwt:
  issuer: gift-certificate-auth-server
  expiration: 24 # in hours
server:
  port: 8081
spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_token_auth
    username: lobur
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
