version: '3.8'

services:
  postgres:
    image: 'postgres:15.2-alpine'
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_SERVER

  gift-certificates:
    build: ./
    image: 'certificates'
    container_name: certificates
    depends_on:
      - postgres
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE
      - APPLICATION_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_URL=jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
