server:
  port: 8080
  ssl:
    enabled: false
spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://oauth2-server:8082
          #jwk-set-uri: http://127.0.0.1:8082/oauth2/jwks
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gifts_dev
    username: lobur
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
